/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  INounsAnonDAOLogicV1,
  INounsAnonDAOLogicV1Interface,
} from "../INounsAnonDAOLogicV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "support",
        type: "uint8",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "castAnonVote",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class INounsAnonDAOLogicV1__factory {
  static readonly abi = _abi;
  static createInterface(): INounsAnonDAOLogicV1Interface {
    return new utils.Interface(_abi) as INounsAnonDAOLogicV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INounsAnonDAOLogicV1 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as INounsAnonDAOLogicV1;
  }
}
